ALTER TABLE scans ADD COLUMN mode TEXT NOT NULL DEFAULT 'baseline';
ALTER TABLE scans ADD COLUMN durationMs INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN riskScore INTEGER NOT NULL DEFAULT 0;
