import { ENV } from "./_core/env";
import { tursoExecute, tursoQuery } from "./turso";

type UserInput = { openId: string; name?: string | null; email?: string | null; loginMethod?: string | null; role?: "user" | "admin"; lastSignedIn?: Date };
export type TursoUser = { id: number; openId: string; name: string | null; email: string | null; loginMethod: string | null; role: "user" | "admin"; createdAt: Date; updatedAt: Date; lastSignedIn: Date };
export type TursoScan = { id: number; userId: number; targetUrl: string; status: "completed" | "failed"; mode: "quick" | "baseline"; criticalCount: number; highCount: number; mediumCount: number; lowCount: number; infoCount: number; summary: string | null; durationMs: number; riskScore: number; createdAt: Date };
export type TursoFinding = { id: number; scanId: number; category: string; severity: "Critical" | "High" | "Medium" | "Low" | "Info"; title: string; description: string; remediation: string; evidence: string | null; owasp: string | null; location: string | null; endpoint: string | null; parameter: string | null; method: string | null; priority: "P0" | "P1" | "P2" | "P3" | null; verification: string | null; createdAt: Date };
const dateOf = (value: unknown) => new Date(Number(value || Date.now()));
const numberOf = (value: unknown) => Number(value || 0);

export async function upsertUser(user: UserInput): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const role = user.role || (user.openId === ENV.ownerOpenId ? "admin" : "user"); const now = Date.now();
  await tursoExecute(`INSERT INTO users (openId,name,email,loginMethod,role,createdAt,updatedAt,lastSignedIn) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(openId) DO UPDATE SET name=excluded.name,email=excluded.email,loginMethod=excluded.loginMethod,role=excluded.role,updatedAt=excluded.updatedAt,lastSignedIn=excluded.lastSignedIn`, [user.openId, user.name ?? null, user.email ?? null, user.loginMethod ?? null, role, now, now, (user.lastSignedIn || new Date()).getTime()]);
}
export async function getUserByOpenId(openId: string): Promise<TursoUser | undefined> { const rows = await tursoQuery<any>("SELECT id,openId,name,email,loginMethod,role,createdAt,updatedAt,lastSignedIn FROM users WHERE openId=? LIMIT 1", [openId]); const row = rows[0]; return row ? { ...row, id: numberOf(row.id), createdAt: dateOf(row.createdAt), updatedAt: dateOf(row.updatedAt), lastSignedIn: dateOf(row.lastSignedIn) } : undefined; }

export async function createScan(userId: number, targetUrl: string, result: { mode: "quick" | "baseline"; durationMs: number; riskScore: number; findings: Array<{ category: string; severity: "Critical" | "High" | "Medium" | "Low" | "Info"; title: string; description: string; remediation: string; evidence?: string; owasp?: string; location?: string; endpoint?: string; parameter?: string; method?: string; priority?: "P0" | "P1" | "P2" | "P3"; verification?: string }> }) {
  const counts = { Critical: 0, High: 0, Medium: 0, Low: 0, Info: 0 }; result.findings.forEach(f => counts[f.severity]++); const now = Date.now();
  const inserted = await tursoQuery<any>("INSERT INTO scans (userId,targetUrl,status,mode,criticalCount,highCount,mediumCount,lowCount,infoCount,summary,durationMs,riskScore,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id", [userId, targetUrl, "completed", result.mode, counts.Critical, counts.High, counts.Medium, counts.Low, counts.Info, `${result.findings.length} finding(s)`, result.durationMs, result.riskScore, now]); const scanId = numberOf(inserted[0]?.id); if (!scanId) throw new Error("Turso did not return a scan id.");
  for (const f of result.findings) await tursoExecute("INSERT INTO findings (scanId,category,severity,title,description,remediation,evidence,owasp,location,endpoint,parameter,method,priority,verification,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [scanId, f.category, f.severity, f.title, f.description, f.remediation, f.evidence ?? null, f.owasp ?? null, f.location ?? null, f.endpoint ?? null, f.parameter ?? null, f.method ?? "GET", f.priority ?? null, f.verification ?? null, now]);
  return scanId;
}
export async function listScans(userId: number): Promise<TursoScan[]> { const rows = await tursoQuery<any>("SELECT * FROM scans WHERE userId=? ORDER BY createdAt DESC LIMIT 50", [userId]); return rows.map(row => ({ ...row, id: numberOf(row.id), userId: numberOf(row.userId), criticalCount: numberOf(row.criticalCount), highCount: numberOf(row.highCount), mediumCount: numberOf(row.mediumCount), lowCount: numberOf(row.lowCount), infoCount: numberOf(row.infoCount), durationMs: numberOf(row.durationMs), riskScore: numberOf(row.riskScore), createdAt: dateOf(row.createdAt) })); }
export async function getScan(userId: number, scanId: number): Promise<{ scan: TursoScan; findings: TursoFinding[] } | undefined> { const scanRows = await tursoQuery<any>("SELECT * FROM scans WHERE id=? AND userId=? LIMIT 1", [scanId, userId]); const row = scanRows[0]; if (!row) return undefined; const findingRows = await tursoQuery<any>("SELECT * FROM findings WHERE scanId=? ORDER BY id ASC", [scanId]); return { scan: { ...row, id: numberOf(row.id), userId: numberOf(row.userId), criticalCount: numberOf(row.criticalCount), highCount: numberOf(row.highCount), mediumCount: numberOf(row.mediumCount), lowCount: numberOf(row.lowCount), infoCount: numberOf(row.infoCount), durationMs: numberOf(row.durationMs), riskScore: numberOf(row.riskScore), createdAt: dateOf(row.createdAt) }, findings: findingRows.map(f => ({ ...f, id: numberOf(f.id), scanId: numberOf(f.scanId), createdAt: dateOf(f.createdAt), owasp: f.owasp ?? null, location: f.location ?? null, endpoint: f.endpoint ?? null, parameter: f.parameter ?? null, method: f.method ?? null, priority: f.priority ?? null, verification: f.verification ?? null })) }; }
