import dns from "node:dns/promises";
import net from "node:net";
import tls from "node:tls";

export type Severity = "Critical" | "High" | "Medium" | "Low" | "Info";
export type Finding = { category: string; severity: Severity; title: string; description: string; remediation: string; evidence?: string; owasp?: string; location?: string; endpoint?: string; parameter?: string; method?: string; priority?: "P0" | "P1" | "P2" | "P3"; verification?: string };
export const severityOrder: Severity[] = ["Critical", "High", "Medium", "Low", "Info"];
const databaseErrorPattern = /(sql syntax|mysql|mariadb|postgresql|sqlite|odbc|ora-\d{4}|syntax error.*near)/i;
export function analyzeSqlProbeResponse(baseline: string, candidate: string, parameter: string, probe: string, status: number): Finding | null { if (databaseErrorPattern.test(candidate) && !databaseErrorPattern.test(baseline)) return { category: "SQLi", severity: "Medium", title: "Database error after safe quote probe", description: "A non-destructive quote probe changed the response into a database-error-like response. Treat this as a review signal, not a confirmed vulnerability.", remediation: "Use prepared statements and consistent server-side validation; inspect the affected parameter in authorized testing.", evidence: `Parameter ${parameter}; probe ${JSON.stringify(probe)} changed status to ${status}.`, parameter, location: "query parameter", method: "GET" }; return null; }
export function analyzeXssReflection(body: string, parameter: string, probe: string) { const raw = body.includes(probe); const marker = probe.split("<")[0]; const escaped = body.includes(`${marker}&lt;probe&gt;`) || body.includes(`${marker}&#x3C;probe&#x3E;`) || body.includes(`${marker}&#60;probe&#62;`) || body.includes(`${marker}\\u003Cprobe\\u003E`); return { raw, escaped, parameter, context: raw ? "raw-html" : escaped ? "escaped-html" : "not-reflected" }; }

const headerChecks = [
  ["content-security-policy", "Content-Security-Policy", "Medium", "A Content-Security-Policy reduces script injection impact by restricting executable sources.", "Define a restrictive policy with nonces or hashes and avoid unsafe-inline where possible."],
  ["x-frame-options", "X-Frame-Options", "Medium", "Without clickjacking protection, pages may be embedded by hostile origins.", "Set DENY or SAMEORIGIN, and use frame-ancestors in CSP for modern deployments."],
  ["strict-transport-security", "Strict-Transport-Security", "High", "Without HSTS, browsers may accept a downgrade to insecure HTTP.", "Serve HTTPS consistently and add Strict-Transport-Security with an appropriate max-age."],
  ["x-content-type-options", "X-Content-Type-Options", "Low", "MIME sniffing can cause browsers to interpret resources in unintended ways.", "Set X-Content-Type-Options: nosniff."],
  ["referrer-policy", "Referrer-Policy", "Low", "An absent policy may disclose URL paths or query data to other origins.", "Set a privacy-preserving policy such as strict-origin-when-cross-origin."],
  ["permissions-policy", "Permissions-Policy", "Low", "An absent policy leaves powerful browser features less explicitly constrained.", "Declare only the camera, microphone, geolocation, and other features the application needs."],
] as const;

export function inspectHeaders(headers: Headers): Finding[] {
  const findings: Finding[] = [];
  for (const [key, label, severity, description, remediation] of headerChecks) if (!headers.get(key)) findings.push({ category: "Headers", severity, title: `${label} is missing`, description, remediation, evidence: `Response did not include ${label}.` });
  return findings;
}
export type ScanMode = "quick" | "baseline";
export function inspectResponseExtras(headers: Headers): Finding[] {
  const findings: Finding[] = [];
  const cors = headers.get("access-control-allow-origin"); const credentials = headers.get("access-control-allow-credentials");
  if (cors === "*") findings.push({ category: "CORS", severity: credentials === "true" ? "High" : "Medium", title: credentials === "true" ? "Wildcard CORS with credentials" : "Wildcard CORS policy", description: "The response permits cross-origin access from any origin, which may expose data if sensitive responses are returned.", remediation: "Allow only explicit trusted origins and avoid credentialed wildcard CORS.", evidence: `Access-Control-Allow-Origin: ${cors}${credentials ? `; credentials: ${credentials}` : ""}` });
  const csp = headers.get("content-security-policy") || ""; if (csp && /unsafe-inline|unsafe-eval|\*/i.test(csp)) findings.push({ category: "CSP", severity: "Medium", title: "CSP contains broad or unsafe source directives", description: "The Content-Security-Policy contains wildcard or unsafe execution directives that can reduce its protection against injection.", remediation: "Replace wildcards and unsafe-inline/unsafe-eval with nonces or hashes and narrowly scoped origins.", evidence: `Content-Security-Policy: ${csp.slice(0, 240)}` });
  const poweredBy = headers.get("x-powered-by"); if (poweredBy) findings.push({ category: "Information Disclosure", severity: "Low", title: "Technology disclosure header present", description: "The response advertises a server technology through X-Powered-By.", remediation: "Remove framework/version disclosure headers at the edge or application server.", evidence: `X-Powered-By: ${poweredBy}` });
  const server = headers.get("server"); if (server && /\d/.test(server)) findings.push({ category: "Information Disclosure", severity: "Info", title: "Server version disclosure indicator", description: "The Server header appears to include version information.", remediation: "Minimize server banner details and keep precise versions out of public responses.", evidence: `Server: ${server}` });
  const setCookie = headers.get("set-cookie");
  if (setCookie) { const cookies = setCookie.split(/,(?=\s*[^;,=]+=[^;,]+)/); for (const cookie of cookies) { const lower = cookie.toLowerCase(); const name = cookie.split("=", 1)[0] || "cookie"; if (!lower.includes("; secure")) findings.push({ category: "Cookies", severity: "Medium", title: `${name} cookie is missing Secure`, description: "A session cookie without Secure may be sent over an unencrypted connection.", remediation: "Set Secure on authentication and session cookies." }); if (!lower.includes("; httponly")) findings.push({ category: "Cookies", severity: "Low", title: `${name} cookie is missing HttpOnly`, description: "A cookie without HttpOnly may be readable by client-side scripts.", remediation: "Set HttpOnly on session cookies that do not need browser script access." }); if (!lower.includes("samesite=")) findings.push({ category: "Cookies", severity: "Low", title: `${name} cookie is missing SameSite`, description: "A cookie without SameSite has less explicit cross-site request protection.", remediation: "Set SameSite=Lax or Strict unless a cross-site flow explicitly requires None." }); } }
  return findings;
}
const owaspByCategory: Record<string, string> = { Headers: "A05:2021 Security Misconfiguration", TLS: "A02:2021 Cryptographic Failures", Cookies: "A07:2021 Identification and Authentication Failures", CORS: "A05:2021 Security Misconfiguration", SQLi: "A03:2021 Injection", "SQLi/XSS": "A03:2021 Injection", XSS: "A03:2021 Injection", Transport: "A05:2021 Security Misconfiguration", Availability: "A05:2021 Security Misconfiguration" };
const priorityBySeverity: Record<Severity, "P0" | "P1" | "P2" | "P3"> = { Critical: "P0", High: "P1", Medium: "P2", Low: "P3", Info: "P3" };
export function enrichFinding(finding: Finding, endpoint = "/"): Finding { return { ...finding, endpoint: finding.endpoint || endpoint, owasp: finding.owasp || owaspByCategory[finding.category] || "A05:2021 Security Misconfiguration", location: finding.location || "HTTP response", method: finding.method || "GET", priority: finding.priority || priorityBySeverity[finding.severity], verification: finding.verification || `Re-test the affected ${finding.category} control after remediation and confirm the response no longer shows this indicator.` }; }
export function inspectUrlIndicators(url: URL): Finding[] { const findings: Finding[] = []; const names = ["url", "uri", "redirect", "next", "return", "dest", "destination", "callback"]; for (const [name, value] of Array.from(url.searchParams.entries())) { if (names.includes(name.toLowerCase()) && /^https?:\/\//i.test(value)) findings.push({ category: "SSRF/Open Redirect", severity: "Info", title: "URL-consuming parameter needs manual review", description: "A public URL parameter appears to accept an absolute URL. This is an indicator for authorized code review, not an exploit attempt.", remediation: "Allow-list destinations, reject unexpected schemes and hosts, and perform server-side URL validation before fetching or redirecting.", evidence: `GET parameter ${name} contains an absolute URL value.` }); } if (/%2e%2e|\.\.\//i.test(url.pathname)) findings.push({ category: "Path Traversal", severity: "Info", title: "Traversal-like path encoding observed", description: "The target path contains an encoded or literal parent-directory sequence. No traversal payload was executed.", remediation: "Canonicalize paths, reject traversal segments, and enforce an allow-listed document root.", evidence: `Path indicator: ${url.pathname.slice(0, 180)}` }); return findings; }
export function calculateRiskScore(findings: Finding[]) { const weights: Record<Severity, number> = { Critical: 40, High: 25, Medium: 12, Low: 5, Info: 0 }; return Math.min(100, findings.reduce((total, finding) => total + weights[finding.severity], 0)); }
export function compareFindings(before: Finding[], after: Finding[]) { const key = (finding: Finding) => `${finding.category}::${finding.title}`; const beforeMap = new Map(before.map(finding => [key(finding), finding])); const afterMap = new Map(after.map(finding => [key(finding), finding])); return { newFindings: after.filter(finding => !beforeMap.has(key(finding))), resolvedFindings: before.filter(finding => !afterMap.has(key(finding))), unchangedFindings: after.filter(finding => beforeMap.has(key(finding))) }; }
function isPrivateAddress(address: string) { if (net.isIPv4(address)) { const [a, b] = address.split(".").map(Number); return a === 10 || a === 127 || a === 0 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168); } if (net.isIPv6(address)) { const normalized = address.toLowerCase(); return normalized === "::1" || normalized.startsWith("fc") || normalized.startsWith("fd") || normalized.startsWith("fe80:"); } return true; }
async function resolvePublicAddresses(hostname: string) { const addresses: string[] = []; let lastError: unknown; for (let attempt = 1; attempt <= 3 && !addresses.length; attempt++) { try { const lookup = dns.lookup(hostname, { all: true }); const timeout = new Promise<never>((_, reject) => setTimeout(() => reject(Object.assign(new Error("DNS lookup timed out"), { code: "EAI_AGAIN" })), 2500)); addresses.push(...(await Promise.race([lookup, timeout])).map(record => record.address)); } catch (error) { lastError = error; if (attempt < 3) await new Promise(resolve => setTimeout(resolve, attempt * 250)); } } if (!addresses.length) { for (const resolver of [dns.resolve4, dns.resolve6]) { try { addresses.push(...await resolver(hostname)); } catch (error) { lastError = error; } } } return { addresses, lastError }; }

export async function validateTarget(raw: string) { let url: URL; const candidate = /^https?:\/\//i.test(raw.trim()) ? raw.trim() : `https://${raw.trim()}`; try { url = new URL(candidate); } catch { throw new Error("Enter a valid public URL, for example https://example.com."); } if (!["http:", "https:"].includes(url.protocol) || url.username || url.password) throw new Error("Only public HTTP(S) URLs without credentials are allowed."); if (url.port && !["80", "443"].includes(url.port)) throw new Error("Only standard HTTP(S) ports are allowed."); if (["localhost", "localhost.localdomain", "0.0.0.0"].includes(url.hostname.toLowerCase()) || url.hostname.endsWith(".local")) throw new Error("Local and private targets are not allowed."); const { addresses, lastError } = await resolvePublicAddresses(url.hostname); if (!addresses.length) { const code = (lastError as NodeJS.ErrnoException | undefined)?.code; if (code === "EAI_AGAIN") throw new Error("The target DNS is temporarily unavailable. Check the hostname and retry in a moment."); if (code === "ENOTFOUND" || code === "ENODATA") throw new Error("The target hostname could not be resolved. Check the URL spelling and DNS records."); throw new Error("The target hostname could not be resolved safely."); } if (addresses.some(isPrivateAddress)) throw new Error("The target resolves to a private or reserved network address."); url.hash = ""; return url; }
async function request(url: URL, init: RequestInit = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 12000); try { return await fetch(url, { ...init, redirect: "manual", signal: controller.signal, headers: { "user-agent": "VibeSecureScanner/1.0 authorized-audit", ...(init.headers || {}) } }); } catch (error) { if ((error as Error).name === "AbortError") throw new Error("The target response timed out after 12 seconds. Confirm the public site is reachable and retry."); if (error instanceof TypeError) throw new Error("The target could not be reached from the scanner. Check DNS, HTTPS, and firewall access."); throw error; } finally { clearTimeout(timer); } }

async function tlsInspection(url: URL): Promise<Finding[]> {
  if (url.protocol !== "https:") return [{ category: "TLS", severity: "High", title: "Target is not using HTTPS", description: "The target URL uses HTTP, so traffic can be observed or modified in transit.", remediation: "Redirect HTTP to HTTPS and update canonical links to HTTPS.", evidence: `${url.protocol}; certificate validity window unavailable because HTTPS was not negotiated.` }];
  return new Promise(resolve => {
    const findings: Finding[] = [];
    const socket = tls.connect({ host: url.hostname, port: Number(url.port || 443), servername: url.hostname, rejectUnauthorized: false, timeout: 7000 }, () => {
      const protocol = socket.getProtocol() || "unknown"; const cipher = socket.getCipher()?.name || "unknown"; const cert = socket.getPeerCertificate(); const validFrom = cert.valid_from ? new Date(cert.valid_from) : null; const validTo = cert.valid_to ? new Date(cert.valid_to) : null; const validityEvidence = `Validity ${validFrom?.toISOString() || "unknown"} → ${validTo?.toISOString() || "unknown"}`;
      if (!socket.authorized) findings.push({ category: "TLS", severity: "High", title: "Certificate is not trusted", description: "The certificate chain was not trusted by the scanner.", remediation: "Install a valid certificate chain from a trusted CA and ensure intermediate certificates are served.", evidence: `${validityEvidence}; ${String(socket.authorizationError || "authorization failed")}` });
      if (validFrom && validFrom.getTime() > Date.now()) findings.push({ category: "TLS", severity: "High", title: "Certificate is not yet valid", description: "The presented certificate validity window begins in the future.", remediation: "Verify server clock and deploy a certificate whose validity window includes the current date.", evidence: `${validityEvidence}; begins in the future` });
      if (validTo && validTo.getTime() < Date.now()) findings.push({ category: "TLS", severity: "Critical", title: "Certificate is expired", description: "The presented certificate is past its validity period.", remediation: "Renew the certificate before expiry and automate renewal monitoring.", evidence: `${validityEvidence}; expired` });
      if (/TLSv1(?:$|\.1)/.test(protocol)) findings.push({ category: "TLS", severity: "High", title: "Legacy TLS protocol detected", description: `The endpoint negotiated ${protocol}, which is a legacy protocol version.`, remediation: "Disable TLS 1.0/1.1 and require TLS 1.2 or newer.", evidence: `${validityEvidence}; ${protocol}` });
      if (/RC4|3DES|DES|NULL|EXPORT|anon/i.test(cipher)) findings.push({ category: "TLS", severity: "High", title: "Weak TLS cipher detected", description: "The negotiated cipher matches a weak or obsolete cipher family.", remediation: "Prefer modern AEAD cipher suites such as AES-GCM or ChaCha20-Poly1305.", evidence: `${validityEvidence}; ${cipher}` });
      if (!findings.length) findings.push({ category: "TLS", severity: "Info", title: "TLS baseline passed", description: `Certificate validity and negotiated transport parameters were inspected (${protocol}, ${cipher}).`, remediation: "Continue monitoring certificate renewal and supported protocol configuration.", evidence: `${validFrom?.toISOString() || "unknown"} → ${validTo?.toISOString() || "unknown"} / ${protocol} / ${cipher}` });
      socket.end(); resolve(findings);
    });
    socket.on("error", error => resolve([{ category: "TLS", severity: "High", title: "TLS inspection failed", description: "The scanner could not complete certificate inspection.", remediation: "Verify that the public HTTPS service is reachable and serves a complete certificate chain.", evidence: `Validity window unavailable; ${error.message}` }]));
    socket.on("timeout", () => { socket.destroy(); resolve([{ category: "TLS", severity: "Medium", title: "TLS inspection timed out", description: "The TLS handshake did not complete within the safe scanner timeout.", remediation: "Check service availability and TLS handshake performance.", evidence: "Validity window unavailable; 7 second timeout" }]); });
  });
}

async function passiveInjectionChecks(url: URL, body: string, findings: Finding[]) {
  const params = Array.from(url.searchParams.keys()).slice(0, 3); const errorPatterns = databaseErrorPattern;
  if (errorPatterns.test(body)) findings.push({ category: "SQLi", severity: "High", title: "Database error disclosure indicator", description: "The baseline response contains recognizable database error text. This is an indicator only and is not proof of exploitability.", remediation: "Return generic error pages, validate inputs server-side, and use parameterized queries everywhere.", evidence: "Database error pattern found in baseline response." });
  if (!params.length) { findings.push({ category: "SQLi/XSS", severity: "Info", title: "No query parameters found", description: "Passive parameter-based indicators were not run because the target URL contains no query parameters.", remediation: "Provide an authorized URL with a known test parameter for deeper passive-style review.", evidence: "No query string" }); return; }
  const parameter = params[0]; const probes = ["'", '"', ")"]; const baselineLength = body.length;
  let sqlSignal = false;
  for (const parameterName of params) for (const probe of probes) { const probeUrl = new URL(url); probeUrl.searchParams.set(parameterName, probe); try { const response = await request(probeUrl); const text = await response.text(); const sqlFinding = analyzeSqlProbeResponse(body, text, parameterName, probe, response.status); if (sqlFinding) { findings.push(sqlFinding); sqlSignal = true; break; } } catch { /* safe probe failure is non-fatal */ } if (sqlSignal) break; }
  const xssProbe = "vibe_probe_7f3a<probe>"; const xssUrl = new URL(url); xssUrl.searchParams.set(parameter, xssProbe); try { const response = await request(xssUrl); const text = await response.text(); const xssAnalysis = analyzeXssReflection(text, parameter, xssProbe); const raw = xssAnalysis.raw; const escaped = xssAnalysis.escaped; if (raw) findings.push({ category: "XSS", severity: "Medium", title: "Unescaped benign probe reflected", description: "A benign marker containing delimiters was reflected without HTML escaping. Context and content type must be reviewed manually.", remediation: "Contextually encode output, use safe templating, validate input, and deploy a restrictive CSP.", evidence: `Context raw-html; marker reflected through query parameter ${parameter}.`, parameter, location: "query parameter", method: "GET" }); else if (escaped) findings.push({ category: "XSS", severity: "Info", title: "Probe reflected with escaping", description: "The benign marker was reflected only after HTML escaping was observed.", remediation: "Keep contextual output encoding and add regression tests for every rendering context.", evidence: `Context escaped-html; marker reflected through query parameter ${parameter}.`, parameter, location: "query parameter", method: "GET" }); if (Math.abs(text.length - baselineLength) > 5000) findings.push({ category: "SQLi", severity: "Info", title: "Response size changed after safe probes", description: "Safe probes produced a materially different response size, which may warrant manual review.", remediation: "Review validation and error handling around the affected parameter.", evidence: `${baselineLength} bytes baseline versus ${text.length} bytes probe response.`, parameter, location: "query parameter", method: "GET" }); } catch { /* safe probe failure is non-fatal */ }
}

export async function runScan(rawUrl: string, mode: ScanMode = "baseline") { const startedAt = Date.now(); const url = await validateTarget(rawUrl); const response = await request(url); const body = await response.text(); const findings: Finding[] = [...inspectHeaders(response.headers), ...inspectResponseExtras(response.headers), ...inspectUrlIndicators(url), ...await tlsInspection(url)]; if (mode === "baseline") await passiveInjectionChecks(url, body, findings); if (response.status >= 500) findings.push({ category: "Availability", severity: "Medium", title: "Server error response", description: `The target returned HTTP ${response.status} during baseline inspection.`, remediation: "Review server logs and ensure error responses do not disclose implementation details.", evidence: `HTTP ${response.status}` }); if (response.status >= 300 && response.status < 400) findings.push({ category: "Transport", severity: "Info", title: "Redirect observed", description: "The target returned a redirect during the baseline request.", remediation: "Confirm redirects are intentional and do not downgrade from HTTPS.", evidence: `HTTP ${response.status}; Location: ${response.headers.get("location") || "not exposed"}` }); if (!findings.length) findings.push({ category: "Baseline", severity: "Info", title: "No indicators detected", description: "The safe baseline checks did not identify a finding in the inspected response.", remediation: "Continue with authenticated testing and code review for deeper assurance.", evidence: `HTTP ${response.status}` }); const ordered = findings.map(finding => enrichFinding(finding, url.pathname || "/")).sort((a, b) => severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity)); return { targetUrl: url.toString(), mode, durationMs: Date.now() - startedAt, riskScore: calculateRiskScore(ordered), findings: ordered, scannedAt: new Date().toISOString() }; }
