import { describe, expect, it } from "vitest";
import { appRouter, makePdf, pdfSafeText, serializeJsonReport } from "./routers";
import { analyzeSqlProbeResponse, analyzeXssReflection, calculateRiskScore, compareFindings, inspectHeaders, inspectResponseExtras, inspectUrlIndicators, severityOrder, validateTarget } from "./scanner";
import { decodeTursoValue } from "./turso";
import type { TrpcContext } from "./_core/context";

const user = { id: 7, openId: "test-user", name: "Test", email: "test@example.com", loginMethod: "test", role: "user" as const, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() };
const ctx = { user, req: {} as TrpcContext["req"], res: {} as TrpcContext["res"] } as TrpcContext;

describe("scanner safety controls", () => {
  it("keeps the required severity hierarchy", () => expect(severityOrder).toEqual(["Critical", "High", "Medium", "Low", "Info"]));
  it("decodes Turso envelopes into React-safe primitives", () => { expect(decodeTursoValue({ type: "null" })).toBeNull(); expect(decodeTursoValue({ type: "integer", value: "7" })).toBe(7); expect(decodeTursoValue({ type: "text", value: "YHA Computer" })).toBe("YHA Computer"); });
  it("reports missing security headers", () => { const findings = inspectHeaders(new Headers()); expect(findings).toHaveLength(6); expect(findings.map(f => f.title)).toContain("Content-Security-Policy is missing"); });
  it("detects wildcard CORS, cookie flags, and caps risk score", () => { const findings = inspectResponseExtras(new Headers({ "access-control-allow-origin": "*", "access-control-allow-credentials": "true", "set-cookie": "sid=abc" })); expect(findings.map(f => f.category)).toContain("CORS"); expect(findings.filter(f => f.category === "Cookies")).toHaveLength(3); expect(calculateRiskScore([{ category: "x", severity: "Critical", title: "x", description: "x", remediation: "x" }, { category: "x", severity: "High", title: "x", description: "x", remediation: "x" }, { category: "x", severity: "Medium", title: "x", description: "x", remediation: "x" }])).toBe(77); });
  it("rejects local targets to reduce SSRF risk", async () => { await expect(validateTarget("http://localhost:3000")).rejects.toThrow(); await expect(validateTarget("http://127.0.0.1")).rejects.toThrow(); });
  it("maps unresolved hostnames to actionable errors", async () => { await expect(validateTarget("https://definitely-not-a-real-host.invalid")).rejects.toThrow(/could not be resolved|DNS is temporarily unavailable/); }, 15000);
  it("rejects scan initiation when acknowledgment is not literal true", async () => { const caller = appRouter.createCaller(ctx); await expect(caller.scans.start({ targetUrl: "https://example.com", acknowledged: false as never })).rejects.toThrow(); });
  it("surfaces actionable DNS errors through scan-start", async () => { const caller = appRouter.createCaller(ctx); await expect(caller.scans.start({ targetUrl: "https://definitely-not-a-real-host.invalid", acknowledged: true })).rejects.toThrow(/could not be resolved|DNS is temporarily unavailable/); }, 15000);
  it("detects safe probe analysis signals", () => { expect(analyzeSqlProbeResponse("ok", "mysql syntax error", "q", "'", 500)?.category).toBe("SQLi"); expect(analyzeXssReflection("vibe_probe_7f3a&lt;probe&gt;", "q", "vibe_probe_7f3a<probe>")).toMatchObject({ raw: false, escaped: true, parameter: "q" }); });
  it("detects safe CSP, disclosure, and URL indicator checks", () => { const headers = new Headers({ "content-security-policy": "default-src * unsafe-inline", "x-powered-by": "Express 4", server: "nginx/1.2" }); expect(inspectResponseExtras(headers).map(f => f.category)).toEqual(expect.arrayContaining(["CSP", "Information Disclosure"])); const indicators = inspectUrlIndicators(new URL("https://example.com/redirect?next=https%3A%2F%2Fother.example")); expect(indicators[0]?.category).toBe("SSRF/Open Redirect"); });
  it("compares findings across scan snapshots", () => { const base = { category: "Headers", severity: "Low" as const, title: "Referrer-Policy is missing", description: "x", remediation: "x" }; const fresh = { category: "CORS", severity: "Medium" as const, title: "Wildcard CORS policy", description: "x", remediation: "x" }; expect(compareFindings([base], [fresh]).newFindings).toHaveLength(1); expect(compareFindings([base], [fresh]).resolvedFindings).toHaveLength(1); });
  it("serializes JSON reports and produces a PDF document", async () => { const sample = { scan: { targetUrl: "https://example.com" }, findings: [{ category: "Headers", severity: "Low", title: "Test", description: "Description", remediation: "Fix" }] } as never; expect(serializeJsonReport(sample)).toContain("example.com"); const pdf = await makePdf(sample); expect(Buffer.from(pdf, "base64").subarray(0, 5).toString()).toBe("%PDF-"); });
  it("normalizes WinAnsi-unsupported glyphs before PDF drawing", async () => { expect(pdfSafeText("Risk → fix — now…")).toBe("Risk -> fix - now..."); const sample = { scan: { targetUrl: "https://example.com", mode: "baseline", riskScore: 22, durationMs: 10 }, findings: [{ category: "Headers", severity: "Low", title: "Arrow → finding", description: "A → B", remediation: "Fix → now", evidence: "x → y" }] } as never; const pdf = await makePdf(sample); expect(Buffer.from(pdf, "base64").subarray(0, 5).toString()).toBe("%PDF-"); });
});
